config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'artworks#index', as: :authenticated_root
  end

  root 'welcome#index'

  devise_for :users,
    path: 'auth',
    path_names: {
      sign_in: 'login',
      sign_up: 'signup',
      sign_out: 'logout'
    },
    controllers: {
      registrations: 'users/registrations'
    }

  resources :images, only: [:update]
  
  resources :users, only: [] do
    resources :artworks
    resource :profile
  end
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  def media_list
    media.join(', ')
  end

  def media_list=(media)
    self.media = media.split(',')
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :artwork
  attachment :file
  acts_as_list scope: :artwork
  default_scope { order(:position) }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  def quote_list
    quotes.join(', ')
  end

  def quote_list=(quotes)
    self.quotes = quotes.split('*')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :artworks

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_params, if: :devise_controller?

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    
  end
  def new
    @artwork = current_user.artworks.new
    @artwork.images.build
  end

  def create
    @artwork = current_user.artworks.new(artwork_params)
    if @artwork.save
      redirect_to user_profile_path(current_user), notice: 'Artwork added'
    else
      flash[:alert] = 'Fail'
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @artwork = @user.artworks.includes(:images).find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @artwork = @user.artworks.includes(:images).find(params[:id])
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :price, :media_list, :quantity,
      images_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def update
    img = Image.find(params[:id])
    img.insert_at(params[:image][:position].to_i)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to user_profile_path
    end
  end

  def show
    @user = User.includes(:profile, artworks: [:images]).find(params[:user_id])
  end

  def edit
  end

  private

  def profile_params
    params.require(:profile).permit(:blurb, :location, :quote_list)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]


  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end  

  def after_sign_up_path_for(resource)
    new_user_profile_path(resource)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def robotar(email)
    image_tag("https://robohash.org/#{email}.png/?size=64x64")
  end

  def foundation_key(key)
    {alert: 'alert', notice: 'primary'}[key.to_sym]
  end

  def lorem_blather
    ((FFaker::BaconIpsum.words(rand(4..8)) << FFaker::CheesyLingo.words(rand(4..8)) << FFaker::HealthcareIpsum.words(rand(4..8)) << FFaker::HipsterIpsum.words(rand(4..8))).shuffle.join(' ')  << '!').capitalize
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artworks/_image_fields.html.haml
.nested-fields
  = f.attachment_field :file, direct: true
  = link_to_remove_association 'remove', f

app/views/artworks/edit.html.haml
.row
  .large-6.columns
    %h3= @artwork.title
    %p= number_to_currency(@artwork.price)
    %p= @artwork.media_list

    .list-group#draggableList
      - @artwork.images.each do |image|
        = div_for(image, class: 'list-group-item') do
          = image_tag(attachment_url(image, :file, :fill, 300, 300))
          %span{ class: 'ion-arrow-move', 'aria-hidden' => 'true'}

  .large-6.columns
    %button.button{"data-toggle" => "explanation-dropdown", type: "button", class: 'explanation-dropdown-button'} How does this work?
    #explanation-dropdown.dropdown-pane{"data-dropdown" => "", "data-hover" => "true", "data-hover-pane" => "true"}
      Grab the image by the pull handle on the right and drag to desired location.  That's it!
    %br/
    = link_to 'View listing', user_artwork_path(@artwork.user, @artwork), class: 'tiny radius button'

app/views/artworks/index.html.haml
%h3 Recently active

- if current_user.profile
  = link_to 'View profile', user_profile_path(current_user)
- else
  = link_to 'Build your profile', new_user_profile_path(current_user)

app/views/artworks/new.html.haml
%h1 New work

= simple_form_for [current_user, @artwork] do |f|

  .form-inputs
    = f.input :title
    = f.input :price
    = f.input :media_list, placeholder: 'Comma separated'

  #images
    = f.simple_fields_for :images do |image|
      = render 'image_fields', f: image
      .links
        = link_to_add_association 'add image', f, :images

  .form-actions
    = f.button :submit

app/views/artworks/show.html.haml
%h3= @artwork.title
%p= @artwork.price
%p= @artwork.media_list
- @artwork.images.each_with_index do |image, idx|
  = div_for(image) do
    - idx == 0 ? dim = 600 : dim = 400
    = image_tag(attachment_url(image, :file, :fill, dim, dim))

= link_to 'edit order', edit_user_artwork_path(@artwork.user, @artwork)

app/views/images/update.js.erb
$('.flash').html("<%= j(render partial: 'shared/ajax_flash', locals: { key: 'notice', value: 'Order updated'}) %>");

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Artiste"

    = stylesheet_link_tag "application"
    = stylesheet_link_tag 'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.4.2/Sortable.min.js'
    = csrf_meta_tag

  %body
    .row
      .large-3.columns
        %h1 Artiste
      .large-9.columns
        .float-right
          - if user_signed_in?
            = link_to 'Sign out', destroy_user_session_path, method: :delete

    .flash
      = render 'shared/messages'

    .row
      .large-10.large-centered.columns
        = yield

app/views/profiles/edit.html.haml
%h1 Profiles#edit
%p Find me in app/views/profiles/edit.html.haml

app/views/profiles/new.html.haml
%h1 Create profile

= simple_form_for [current_user, @profile], url: user_profile_path do |f|
  .form-inputs
    = f.input :blurb
    = f.input :quote_list, placeholder: 'Asterisk separated'
    = f.input :location
  .form-actions
    = f.button :submit, 'Create profile', class: 'tiny radius button'

app/views/profiles/show.html.haml
%h1= @user.full_name

.callout.primary
  = @user.profile.blurb

- @user.profile.quotes.each do |quote|
  .media-object
    .media-object-section
      .thumbnail
        = robotar(@user.email)
    .media-object-section
      %em= quote

%h4
  Location:
  = @user.profile.location

%h4 Artworks
= link_to 'Add a new work', new_user_artwork_path(current_user)
- if @user.artworks.any?
  - @user.artworks.each do |artwork|
    .media-object
      %h3= artwork.title
      %p= artwork.price
      %p= artwork.media_list
      %figure.marquee-artwork
        = image_tag(attachment_url(artwork.images.first, :file, :fill, 400, 400))
    = link_to 'View artwork', [artwork.user, artwork]
- else
  No art here

app/views/shared/_ajax_flash.html.haml
%div{class: "small callout #{foundation_key(key)}"}
  = value

app/views/shared/_messages.html.haml
- flash.each do |k,v|
  %div{class: "flash small callout #{foundation_key(k)}"}
    = v

app/views/welcome/index.html.haml
.callout
  = lorem_blather
.auth-links
  = link_to 'Sign up', new_user_registration_path, class: 'tiny radius button'
  = link_to 'Sign in', new_user_session_path, class: 'tiny radius button'